---

###############################################################################
#                                                                             #
# Ansible Hardening lab                                                       #
# Target: rhel 7/8                                                            #
# version: 1.0                                                                #
#                                                                             #
#                                                                             #
# Writen by : Diego A. Zarate (PCS_X86 Team)                                  #
#                                                                             #
###############################################################################





- name: OpenScap Report ITSS Policy
  hosts: all
  gather_facts: true
  strategy: free
  vars:
    data_stream_home: "/usr/share/xml/scap/ssg/content/"
    report_name: "pam-Report"
    report_name2: "login-def-report"
    report_dest: "/etc/ansible/playbooks/policies/hardening_reports/"

  tasks:

     - name: update min len on  RHEL7
       shell: authconfig --passminlen=15 --update
       when: ansible_distribution_major_version == "7"

     - name: update min len on  RHEL8
       lineinfile:
               path: /etc/security/pwquality.conf
               regexp: '^minlen'
               line: minlen = 15
               owner: root
               group: root
               mode: 0644
       when: ansible_distribution_major_version == "8"

     - name: change root max day password cahng
       shell: chage root -M 90

     - name: report pam
       shell: egrep "^lcredit|^ucredit|^dcredit|^ocredit|^minlen" /etc/security/pwquality.conf > /tmp/{{ inventory_hostname }}-{{ report_name }}.txt

     - name: report login defs
       shell: egrep "^PASS_MAX_DAYS|^PASS_MIN_DAYS|^PASS_WARN_AGE" /etc/login.defs > /tmp/{{ inventory_hostname }}-{{ report_name2 }}.txt

     - name: CP report
       fetch:
        src: /tmp/{{ inventory_hostname }}-{{ report_name }}.txt
        dest: "{{ report_dest }}"

        flat: yes

     - name: CP report
       fetch:
        src: /tmp/{{ inventory_hostname }}-{{ report_name2 }}.txt
        dest: "{{ report_dest }}"

        flat: yes

     - name: Clean Report
       file:
        path: /tmp/{{ inventory_hostname }}-{{ report_name }}.txt
        state: absent

     - name: Clean Report
       file:
        path: /tmp/{{ inventory_hostname }}-{{ report_name2 }}.txt
        state: absent



     - name: Send email
       mail:
         host: localhost
         port: 25
         to: REDHAT.r556besbztong202@u.box.com
         subject: mail
         body: mail
         attach:
         - "{{ report_dest }}{{ inventory_hostname }}-{{ report_name }}.txt"
         - "{{ report_dest }}{{ inventory_hostname }}-{{ report_name2 }}.txt"
       delegate_to: localhost
...
