---

###############################################################################
#                                                                             #
# Ansible Hardening lab                                                       #
# Target: rhel 7/8                                                            #
# version: 1.0                                                                #
#                                                                             #
#                                                                             #
# Writen by : Diego A. Zarate (PCS_X86 Team)                                  #
#                                                                             #
###############################################################################

- name: Hosts setup for oscap scan 
  hosts: all
  gather_facts: true
  strategy: free
  vars:
    data_stream_home: "/usr/share/xml/scap/ssg/content/"
    src_profile: "/etc/ansible/playbooks/policies/"
    profile7: "ssg-rhel7-ds-tailoring.xml"
    profile8: "ssg-rhel8-ds-tailoring.xml"

  tasks:
    - name: Install necesary packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - openscap-scanner
        - scap-security-guide

    - name: Copy custom policies to RHEL Version "{{ ansible_distribution_major_version }}"
      copy:
        src: "{{ src_profile }}ssg-rhel{{ ansible_distribution_major_version }}-ds-tailoring.xml"
        dest: "{{ data_stream_home }}"
        mode: 775
...
     

