---

###############################################################################
#                                                                             #
# Ansible Hardening lab                                                       #
# Target: rhel 7/8                                                            #
# version: 1.0                                                                #
#                                                                             #
#                                                                             #
# Writen by : Diego A. Zarate (PCS_X86 Team)                                  #
#                                                                             #
###############################################################################





- name: OpenScap Report ITSS Policy
  hosts: all
  gather_facts: true
  strategy: free
  vars:
    data_stream_home: "/usr/share/xml/scap/ssg/content/"
    report_name: "User-Report"
    report_dest: "/etc/ansible/playbooks/policies/hardening_reports/"

  tasks:

     - name: Run Scap OSCAP RHEL7
       shell: cat /etc/passwd > /tmp/{{ inventory_hostname }}-{{ report_name }}.txt 
       when: ansible_distribution_major_version == "7"
       ignore_errors: yes

     - name: Run Scap OSCAP RHEL8
       shell: cat /etc/passwd > /tmp/{{ inventory_hostname }}-{{ report_name }}.txt
       when: ansible_distribution_major_version == "8"
       ignore_errors: yes

     - name: CP report
       fetch:
        src: /tmp/{{ inventory_hostname }}-{{ report_name }}.txt
        dest: "{{ report_dest }}"

        flat: yes

     - name: Clean Report
       file:
        path: /tmp/{{ inventory_hostname }}-{{ report_name }}.txt
        state: absent


     - name: Send email
       mail:
         host: localhost
         port: 25
         to: REDHAT.r556besbztong202@u.box.com
         subject: mail
         body: mail
         attach:
         - "{{ report_dest }}{{ inventory_hostname }}-{{ report_name }}.txt"
       delegate_to: localhost
...
